### ISSUE TITLE
How to run the project on local machine? DB migration and, etc.

### ISSUE THREAD

**Issue by MarshalOfficial** [itswadesh/svelte-commerce#40]
Hi there, I want to run the project after clone but I have errors, it seems that backend API and DB migration didn't do. Could you please help me with how can I do this?

**Comment by itswadesh** [comment]
Hi Marshal,

Can you please try it now. We have a new version and it should have fixed the issue

**Comment by heiheshang** [comment]
I don't understand how to compile the project

**Comment by itswadesh** [comment]
git clone git@github.com:itswadesh/svelte-commerce.git
cd svelte-commerce
npm i
npm run dev

**Comment by heiheshang** [comment]
npm run build does not collect anything

**Comment by itswadesh** [comment]
Can you please share the screenshot

**Comment by heiheshang** [comment]
`Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
Error: Cannot access url.searchParams on a page with prerendering enabled
    at URL.get [as searchParams] (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:704:15)
    at load (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:18:26)
    at load_server_data (file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:725:71)
    at file:///home/oper/Programs/svelte-commerce/.svelte-kit/output/server/index.js:1514:24
file:///home/oper/Programs/svelte-commerce/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:50
				throw new Error(format_error(details, config));
				      ^

Error: 500 /
    at file:///home/oper/Programs/svelte-commerce/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:50:11
    at save (file:///home/oper/Programs/svelte-commerce/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:361:4)
    at visit (file:///home/oper/Programs/svelte-commerce/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:232:3)
[vite-plugin-svelte-kit] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///home/oper/Programs/svelte-commerce/node_modules/@sveltejs/kit/src/exports/vite/index.js:438:15)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)`

**Comment by itswadesh** [comment]
Hi I guess you are probably missing the following step
``` Make a copy of .env.example and rename to .env ```

**Comment by heiheshang** [comment]
did not help
